# Generated by Django 3.2.13 on 2022-05-27 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationdetail',
            name='operation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
