# Generated by Django 3.2.13 on 2022-05-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_alter_operationdetail_operation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationdetail',
            name='operation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
