# Generated by Django 3.2.13 on 2022-05-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmdbmovie',
            name='movie_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
