# Generated by Django 3.2.13 on 2022-05-27 08:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tmdb', '0004_auto_20220527_0631'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='watchlist',
            name='user_movie_unique',
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user_id', 'movie_id')},
        ),
    ]
