# Generated by Django 3.2.13 on 2022-05-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0006_auto_20220527_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
